server {
    listen 4000;
    server_name localhost;

    root /usr/share/nginx/html;

    # Sentry + instrumentation to capture simulator iframe src bug.
    # Some clients request /simulator instead of /simulator.html (root cause unknown).
    sub_filter '</head>' '<script src="https://js.sentry-cdn.com/0c8cac44c07684296c74b874d8775d63.min.js" crossorigin="anonymous"></script><script src="/instrumentation.js"></script></head>';
    sub_filter_once on;
    sub_filter_types text/html;

    location / {
        gzip_static on;
        try_files $uri /index.html;
    }
}
