name: Build Makecode Dev

on:
  push:
    branches: [develop]

jobs:

  build:
    uses: team-monolith-product/tmn-gh-actions/.github/workflows/build_v2.yml@develop
    with:
      env: dev
      target: develop
      updateTargets: |
        {
          "aws": {
            "imageName": "jce-ecr-pxt-microbit-all-dev",
            "valueFilePath": ["makecode/aws-apne2-dev-service.yaml"]
          }
        }
    secrets:
      MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
