name: Deploy to Develop

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    uses: team-monolith-product/tmn-gh-actions/.github/workflows/deploy.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      comment_id: ${{ github.event.comment.id }}
      comment_body: ${{ github.event.comment.body }}
    secrets:
      MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
